CREATE TABLE ACT_GE_SOCIAL_INFORMATION (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  PROCESS_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  KEY_ varchar(255) COLLATE utf8_bin DEFAULT NULL,
  RATING_VALUE_ double unsigned zerofill DEFAULT '0000000000000000000000',
  RATING_ABSOLUTE_ double unsigned zerofill DEFAULT '0000000000000000000000',
  OWNER_ID_ varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_IDX_SOCIAL_INFORMATION_PROCESSID (PROCESS_ID_),
  KEY ACT_IDX_SOCIAL_INFORMATION_KEY (KEY_)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_SOCIAL_PROFILE (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  USER_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  NAME_ varchar(64) COLLATE utf8_bin NOT NULL,
  EMAIL_ varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_WIKI (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  PROCESS_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  CREATOR_ID_ varchar(64) COLLATE utf8_bin DEFAULT NULL,
  CREATION_TIME_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PROCESS_NAME_ varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_SOCIAL_INFORMATION_WIKI_idx (PROCESS_ID_),
  KEY ACT_IDX_WIKI_PROCESS_NAME (PROCESS_NAME_),
  CONSTRAINT ACT_FK_SOCIAL_INFORMATION_WIKI FOREIGN KEY (PROCESS_ID_) REFERENCES ACT_GE_SOCIAL_INFORMATION (PROCESS_ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_PART (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  TITLE_ varchar(255) COLLATE utf8_bin NOT NULL,
  BODY_ varchar(4000) COLLATE utf8_bin NOT NULL,
  CREATION_TIME_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  CREATOR_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  WIKI_ID_ int(11) DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_PART_WIKI_ID_idx (WIKI_ID_),
  CONSTRAINT ACT_FK_PART_WIKI_ID FOREIGN KEY (WIKI_ID_) REFERENCES ACT_GE_WIKI (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_REVISION (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  REVISION_ int(11) NOT NULL,
  BODY_ varchar(4000) COLLATE utf8_bin NOT NULL,
  MODIFIER_ID_ varchar(64) COLLATE utf8_bin DEFAULT NULL,
  CREATION_TIME_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PART_ID_ int(11) DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_REVISION_PART_ID_idx (PART_ID_),
  CONSTRAINT ACT_FK_REVISION_PART_ID FOREIGN KEY (PART_ID_) REFERENCES ACT_GE_PART (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_REPORT (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  PROCESS_ID_ varchar(64) COLLATE utf8_bin DEFAULT NULL,
  CREATION_DATE_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  TOPIC_ varchar(255) COLLATE utf8_bin NOT NULL,
  MESSAGE_ varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  REPORTER_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  STATUS_ int(11) NOT NULL,
  UPVOTES_ int(11) DEFAULT '0',
  TYPE_ varchar(45) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_IDX_REPORT_PROCESSID (PROCESS_ID_),
  KEY ACT_IDX_REPORT_TOPIC (TOPIC_),
  KEY ACT_IDX_REPORT_TYPE (TYPE_),
  CONSTRAINT ACT_FK_SOCIAL_INFORMATION_REPORT FOREIGN KEY (PROCESS_ID_) REFERENCES ACT_GE_SOCIAL_INFORMATION (PROCESS_ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_COMMENT (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  REPORTER_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  CREATION_TIME_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  MESSAGE_ varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  REPORT_ID_ int(11) DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_COMMENT_REPORT_ID_idx (REPORT_ID_),
  CONSTRAINT ACT_FK_COMMENT_REPORT_ID FOREIGN KEY (REPORT_ID_) REFERENCES ACT_GE_REPORT (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_DEVELOPER (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  SOCIAL_INFO_ID_ int(11) DEFAULT NULL,
  USER_ID_ varchar(45) COLLATE utf8_bin NOT NULL,
  EMAIL_ varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_SOCIAL_INFORMATION_DEVELOPER_idx (SOCIAL_INFO_ID_),
  CONSTRAINT ACT_FK_SOCIAL_INFORMATION_DEVELOPER FOREIGN KEY (SOCIAL_INFO_ID_) REFERENCES ACT_GE_SOCIAL_INFORMATION (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_NEWS (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  ACTOR_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  TYPE_ varchar(45) COLLATE utf8_bin NOT NULL,
  ACTION_ varchar(45) COLLATE utf8_bin NOT NULL,
  OBJECT_KEY_ int(11) NOT NULL,
  CREATION_TIME_ timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  OBJECT_REF_ varchar(64) COLLATE utf8_bin NOT NULL,
  TITLE_ varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_IDX_NEWS_OBJECT_KEY (OBJECT_KEY_)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_RATER (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  RATER_ID_ varchar(64) COLLATE utf8_bin NOT NULL,
  RATING_ double DEFAULT NULL,
  SOCIAL_INFO_ID_ int(11) NOT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_RATER_SOCIAL_INFO_ID__idx (SOCIAL_INFO_ID_),
  CONSTRAINT ACT_FK_RATER_SOCIAL_INFO_ID_ FOREIGN KEY (SOCIAL_INFO_ID_) REFERENCES ACT_GE_SOCIAL_INFORMATION (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_TAGS (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  SOCIAL_INFO_ID_ int(11) NOT NULL,
  NAME_ varchar(64) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_SOCIAL_INFORMATION_TAGS_idx (SOCIAL_INFO_ID_),
  CONSTRAINT ACT_FK_SOCIAL_INFORMATION_TAGS FOREIGN KEY (SOCIAL_INFO_ID_) REFERENCES ACT_GE_SOCIAL_INFORMATION (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ACT_GE_FEED (
  ID_ int(11) NOT NULL AUTO_INCREMENT,
  PROFILE_ID_ int(11) NOT NULL,
  OBJECT_KEY_ int(11) NOT NULL,
  TYPE_ varchar(45) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (ID_),
  KEY ACT_FK_FEED_PROFILE_ID__idx (PROFILE_ID_),
  CONSTRAINT ACT_FK_FEED_PROFILE_ID_ FOREIGN KEY (PROFILE_ID_) REFERENCES ACT_GE_SOCIAL_PROFILE (ID_) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

